const FLAG_CODES: Record<string, string> = {
  // América del Sur
  Argentina: 'ar',
  Bolivia: 'bo',
  Brasil: 'br',
  Chile: 'cl',
  Colombia: 'co',
  Ecuador: 'ec',
  Paraguay: 'py',
  Perú: 'pe',
  Uruguay: 'uy',
  Venezuela: 've',
  // América del Norte y Central
  Canadá: 'ca',
  'Costa Rica': 'cr',
  'Estados Unidos': 'us',
  Haití: 'ht',
  Honduras: 'hn',
  Jamaica: 'jm',
  México: 'mx',
  Panamá: 'pa',
  // Europa
  Alemania: 'de',
  Austria: 'at',
  Bélgica: 'be',
  'Bosnia y Herz.': 'ba',
  Croacia: 'hr',
  Dinamarca: 'dk',
  Escocia: 'gb-sct',
  Eslovaquia: 'sk',
  España: 'es',
  Francia: 'fr',
  Gales: 'gb-wls',
  Inglaterra: 'gb-eng',
  Irlanda: 'ie',
  'Irlanda del Norte': 'gb-nir',
  Noruega: 'no',
  'Países Bajos': 'nl',
  Polonia: 'pl',
  Portugal: 'pt',
  'República Checa': 'cz',
  Serbia: 'rs',
  Suecia: 'se',
  Suiza: 'ch',
  Turquía: 'tr',
  Ucrania: 'ua',
  // África
  Argelia: 'dz',
  Camerún: 'cm',
  'Cabo Verde': 'cv',
  'Costa de Marfil': 'ci',
  Egipto: 'eg',
  Ghana: 'gh',
  Marruecos: 'ma',
  Nigeria: 'ng',
  'Rep. D. del Congo': 'cd',
  Senegal: 'sn',
  Sudáfrica: 'za',
  Túnez: 'tn',
  // Asia / Oceanía / Medio Oriente
  'Arabia Saudita': 'sa',
  Australia: 'au',
  Catar: 'qa',
  Corea: 'kr',
  'Corea del Sur': 'kr',
  Irak: 'iq',
  Irán: 'ir',
  Japón: 'jp',
  Jordania: 'jo',
  'Nueva Zelanda': 'nz',
  Uzbekistán: 'uz',
  // Caribe
  Curaçao: 'cw',
}

export function getFlagCode(teamName: string): string | null {
  return FLAG_CODES[teamName] ?? null
}
